services:
  api:
    build: .
    image: hello-api:0.1.0
    environment:
      ENV: prod
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 30s
      timeout: 5s	
      retries: 3
